### PR TITLE
56389 - [Issue 183] (Android) Manual whitelisting of app on Android

### PR DESCRIPTION
**Pull request by ant3k96**
I added background activity dialog, which asks user whether to turn off battery life optimisation for Smittestopp app. I used a default Android App AlertDialog, which I implemented in uncalled method ShowBackgroundActivityDialog in InfectionStatusActivity. Method is called after pressing Activate EN button  Screenshot of the dialog below. 

Screenshot 2021-04-30 at 11 15 25

**Yes** - will show native dialog which when confirmed will disable battery optimization for the app,
**No** - will close a dialog,
**No, do not show this again** - will close a dialog until next update of the app or if user reinstalls it.

To allow this automatic request to ignore battery optimizations a permission was added to AndroidManifest.

There is also possibility to whitelist app from general settings view. Screenshot of the view below.

Screenshot general settings

**Enabling** button will cause the same result as clicking Yes button on background activity dialog.
**Disabling** button will navigate user to Settings->Special access->Optimize battery usage where battery optimization can be turn on manually.

There is also automatic keys pull every time user opens application.

### CODE REVIEW

**Comment by nc-kano** [comment]
And what with "Do not ahow again" option?

**Comment by ant3k96** [comment]
So this button should close and never show dialog to a user.

**Comment by Michael-Olesen** [comment]
The buttons on the dialog should probably have the same color as the rest of the dialog buttons in the app.

**Comment by ant3k96** [comment]
Ok I will change that.

**Review by nc-kano — COMMENTED** [review]
Approve for the code. But i am still not sure about UI design. What does it mean "do not show again"? Is it "No, and do not show again" or "Yes, and do not show again"?

**Comment by Michael-Olesen** [comment]
Agree with Kamil should probably be "No, and do not show again" - since the other formulation might be confusing - also I do not think the dialog should be shown again after an update of the app, if the user has pressed "No, and do not show again" before, if it is possible.

**Comment by ant3k96** [comment]
Yes, you are right. I will implement that.

**Review by Michael-Olesen — APPROVED** [review]

**Pull request merged**
