### PR TITLE
[50272] Remove not needed sign

### PR DESCRIPTION
**Pull request by nc-kano**

### CODE REVIEW

**Comment by nc-kano** [comment]
Spreadsheet updated

**Comment by Frederik-S-N-dk** [comment]
Have you tried to run the solution with this change? Because mine couldn't build it when I did this change

**Comment by nc-kano** [comment]
@Frederik-S-N-dk yes, no problems:
Screenshot_1606820248

**Review by jonasofrich — APPROVED** [review]
Tested OK here as well

**Pull request merged**
