### PR TITLE
[54075] Fixed .no in the email address being read wrong in NB and EN, other languages remain unchanged

### PR DESCRIPTION
**Pull request by pavshr**

### CODE REVIEW

**Comment by pavshr** [comment]
@Frederik-S-N-dk text files still need to be updated :)

**Review by Frederik-S-N-dk — APPROVED** [review]
Excel sheet has been updated

**Comment by Frederik-S-N-dk** [comment]
@pavshr Is it on purpose that this PR still have "do not merge"?

**Comment by pavshr** [comment]
Was do not merge until you added texts @Frederik-S-N-dk . Appreciated :)

**Pull request merged**
