### PR TITLE
Added time skew to JWT-validation

### PR DESCRIPTION
**Pull request by sindremb**
Due to some devices experiencing that the JWT-token validation fails with the reason "token is not valid yet" I have added an allowed time skew to the token validation of 5 minutes.

5 minutes was chosen, [as this seems to be the default on other implementations](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6c94a28fb638c118c10e020d63ef5c6782d80a7d/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L134).

Time skew is only available in the latest version of the JWT-package (7.3.1), so this had to be updated as well.

It could also be beneficial to make this value configurable, but this is not implemented in this pull request for now.

### CODE REVIEW

**Review by nc-kano — APPROVED** [review]

**Comment by sindremb** [comment]
I guess this should be merged and verified by one of the app devs, as I have not been able to run and verify the fix my self.

**Comment by sindremb** [comment]
I assume this pull request can now be discarded, as the issue it was trying to resolve is no longer present?

**Comment by nc-kano** [comment]
@sindremb @pavshr i had this issue again and this PR fixed the issue. so i think we should merge it

**Comment by sindremb** [comment]
We got some indications that this error may still be present

**Pull request merged**
