### PR TITLE
Change colors on Force Update page

### PR DESCRIPTION
**Pull request by nc-kano**

### CODE REVIEW

**Comment by nc-kano** [comment]
Zrzut ekranu 2021-01-11 o 15 42 56
Zrzut ekranu 2021-01-11 o 15 36 01

**Review by pavshr — COMMENTED** [review]
Shouldn't wee merge it into dev_rx1 branch?

**Comment by Frederik-S-N-dk** [comment]
> Shouldn't wee merge it into dev_rx1 branch?

Let's wait and see until we have decided that in 1 hour :)

**Comment by CUSL78** [comment]
Should it be a FHI logo on these screenshots? @Frederik-S-N-dk

**Comment by Frederik-S-N-dk** [comment]
> Should it be a FHI logo on these screenshots? @Frederik-S-N-dk

We will discuss that on todays meeting :-)

**Comment by CUSL78** [comment]
Great thanks 😊

Fra: Frederik Skou Nielsen <notifications@github.com>
Sendt: tirsdag 12. januar 2021 10:38
Til: folkehelseinstituttet/Fhi.Smittestopp.App <Fhi.Smittestopp.App@noreply.github.com>
Kopi: Christine Lunde <christine.ursin.steen.lunde@nhn.no>; Comment <comment@noreply.github.com>
Emne: Re: [folkehelseinstituttet/Fhi.Smittestopp.App] Change colors on Force Update page (#229)


Should it be a FHI logo on these screenshots? @Frederik-S-N-dk<https://github.com/Frederik-S-N-dk>

We will discuss that on todays meeting :-)

**Comment by Frederik-S-N-dk** [comment]
Let's merge this PR - and then handle any needed changes in a new PR.

**Review by Frederik-S-N-dk — APPROVED** [review]

**Pull request merged**
