### PR TITLE
[50497] Correct consents button for large font sizes

### PR DESCRIPTION
**Pull request by nc-kano**

### CODE REVIEW

**Review by jonasofrich — CHANGES_REQUESTED** [review]
Can you get the text to stay inside the button? This is iPhone 11 with font at max size

IMG_0161

**Comment by nc-kano** [comment]
@jonasofrich this is a different page

**Comment by nc-kano** [comment]
This is how it looks for the smallest and the greatest font:
BD121957-0295-4204-B9CB-A44F126D6436
7C72091E-FA07-461E-8647-DBDC5BC0E377

**Comment by nc-kano** [comment]
@jonasofrich now the fix also includes the burger menu consents page
2A86A325-AACC-4373-A915-8E04B8922AF6

**Comment by jonasofrich** [comment]
@nc-kano still looks pretty much the same as my first screenshot for me on both pages

**Comment by nc-kano** [comment]
@jonasofrich how is that possible? for me it looks:
Simulator Screen Shot - iPhone 11 - 2020-12-03 at 16 04 50
Simulator Screen Shot - iPhone 11 - 2020-12-03 at 16 03 55

**Comment by jonasofrich** [comment]
@nc-kano I think I must have done something wrong when building and deploying. Retried now, and it looks great! 🥇

**Review by jonasofrich — APPROVED** [review]

**Pull request merged**
