### PR TITLE
[50446] Overlapping buttons on start screen for ios

### PR DESCRIPTION
**Pull request by TMHolen95**
Fixes issue where the "Continue in English" button was overlapping with the Nynorsk button. 

__Implementation notes:__
Converted the Storyboard to use a StackView solution for the components, so the spacing is dynamically resized depending on the available screen estate, as this is more user friendly than introducing a ScrollView (which probably would hide the "Continue in english button").

__Reviewers:__
I would appreciate if reviewers checked that the storyboard displays correct on their device, i have checked it on my iPhone SE 1 Gen and a simulator iPhone 12 Pro.

__Screenshots:__

iPhone SE 1 Gen:
iPhone SE 1 Gen Accessibility OFF copy   iPhone SE 1 Gen Accessibility ON copy

iPhone 12 Pro Simulator:
iPhone 12 Pro Accessibility OFF copy   iPhone 12 Pro Accessibility ON copy

### CODE REVIEW

**Review by jonasofrich — APPROVED** [review]
Looks good on iPhone 11 (14.2) :)

**Review by Frederik-S-N-dk — APPROVED** [review]
Looks good on iPhone Xs (14.2)

**Comment by TMHolen95** [comment]
Perfect, then it sounds safe to merge 👍

**Review by pavshr — APPROVED** [review]
Approved :)

**Pull request merged**
