### PR TITLE
WIP: Added Bokmål, Nynorsk and English

### PR DESCRIPTION
**Pull request by pavshr**
New texts for users who might end up installing Smittestop on unsupported version of iOS.

### CODE REVIEW

**Comment by pavshr** [comment]
Awaiting other translations before merge

**Comment by Frederik-S-N-dk** [comment]
@pavshr Have you updated the excel sheet as well?

**Comment by pavshr** [comment]
Not yet, I am waiting for rest of translations

**Comment by Frederik-S-N-dk** [comment]
@pavshr We should close this PR and instead have a complete update of texts for all languages in another PR whenever these are ready. This will be in relation to sending the app for the translators/testers.

**Comment by pavshr** [comment]
@Frederik-S-N-dk I do not get it, why can't I just add missing texts in this PR since it is not merged yet? :)

**Comment by Frederik-S-N-dk** [comment]
@pavshr We can have the entire text update within this sheet :)

**Comment by Frederik-S-N-dk** [comment]
This PR is now out-dated. I will close it.

**Pull request closed without merging**
