### PR TITLE
[48446] - iOS,  Questionnaire page

### PR DESCRIPTION
**Pull request by fsnNC**
image

### CODE REVIEW

**Comment by nc-kano** [comment]
@fsnNC Why quiestionnaire view shows date twice? there is such thing in sketches

**Comment by fsnNC** [comment]
@nc-kano: Is by default the way it's done in iOS. I just changed the colors and borders of it and kept the functionality as in the DK app

**Comment by pavshr** [comment]
> @fsnNC Why quiestionnaire view shows date twice? there is such thing in sketches

This is because of the new way to show calender in iOS since iOS 14. Since we are building now in Xcode 12, this comes by default.

**Comment by fsnNC** [comment]
> > @fsnNC Why quiestionnaire view shows date twice? there is such thing in sketches
> 
> This is because of the new way to show datepicker in iOS since iOS 14. Since we are building now in Xcode 12, this comes by default.
> 
> We can however enforce wheels-style datepicker to choose the date.

@nc-kano Let's approve this design since it's the default way. Then I'll create a bug stating that we should look into a more pretty/user-friendly way of displaying the calendar on iOS

**Pull request merged**
