### PR TITLE
[53777] iOS: Add new page "Dagens tall" - new UI changes

### PR DESCRIPTION
**Pull request by MIKKH**
EDIT! Updated screenshots
Updated UI to match latest design.

Screenshots (updated):

Screenshot 2021-02-26 at 14 48 01
Screenshot 2021-02-26 at 14 48 11
Screenshot 2021-02-26 at 14 48 25

### CODE REVIEW

**Review by jonasofrich — CHANGES_REQUESTED** [review]
Change the color of the X-button, and maybe decrease the spacing at the top of the screen

**Comment by Frederik-S-N-dk** [comment]
@MIKKH There should not be any +-sign in relation to the daily changes. 
Please see the design of this page on the related PBI.

**Comment by MIKKH** [comment]
> @MIKKH There should not be any +-sign in relation to the daily changes.
> Please see the design of this page on the related PBI.

@Frederik-S-N-dk Texts should be updated in the Excel sheet and new locales generated.

**Comment by MIKKH** [comment]
> Change the color of the X-button, and maybe decrease the spacing at the top of the screen

@jonasofrich I have changed the color of the back button, and reduced the size of top area.

**Review by jonasofrich — APPROVED** [review]

**Pull request merged**
